openapi: 3.0.3
info:
  title: Country Management API
  version: 1.0.0
  description: API for managing countries around the world

servers:
  - url: '{protocol}://{host}:{port}/countries-service/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      host:
        default: 'localhost'
      port:
        default: '8080'

paths:
  /countries:
    get:
      summary: Retrieve a list of all countries
      operationId: getAllCountries
      responses:
        '200':
          description: A list of all countries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
        '404':
          description: No countries found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Add a new country to the list
      operationId: addCountry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CountryInput'
      responses:
        '201':
          description: The newly created country
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '400':
          description: Input data is bad formatted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /countries/{id}:
    parameters:
      - $ref: '#/components/parameters/CountryId'
    get:
      summary: Retrieve details for a specific country
      operationId: getCountryById
      responses:
        '200':
          description: Details for the specified country
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '404':
          description: Country not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update an existing country
      operationId: updateCountryById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CountryInput'
      responses:
        '200':
          description: The updated country
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '400':
          description: Input data is bad formatted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Country not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a country from the list
      operationId: deleteCountryById
      responses:
        '204':
          description: Country deleted successfully
        '404':
          description: Country not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /countries/{id}/population:
    parameters:
      - $ref: '#/components/parameters/CountryId'
    get:
      summary: Retrieve population data for a specific country
      operationId: getCountryPopulationById
      responses:
        '200':
          description: Population data for the specified country
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryPopulation'
        '404':
          description: Country not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  parameters:
    CountryId:
      name: id
      in: path
      description: ID of the country to retrieve
      required: true
      schema:
        type: integer

  schemas:
    CountryDetails:
      type: object
      properties:
        name:
          type: string
          description: Name of the country
        capital:
          type: string
          description: Capital city of the country
        region:
          type: string
          description: Geographic region the country belongs to
        population:
          type: integer
          format: int64
          description: Total population of the country
        area:
          type: integer
          format: int64
          description: Total area of the country in square kilometers
        languages:
          type: array
          items:
            type: string
          description: List of official languages spoken in the country
        flag:
          type: string
          description: URL to the country's national flag image

    Country:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier of the country
        details:
          $ref: '#/components/schemas/CountryDetails'
      example:
        id: 1
        details:
          name: "Australia"
          capital: "Canberra"
          region: "Oceania"
          population: 25649909
          area: 7692024
          languages: [ "English" ]
          flag: https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Australia.svg

    CountryInput:
      type: object
      properties:
        details:
          $ref: '#/components/schemas/CountryDetails'
      example:
        details:
          name: "Canada"
          capital: "Ottawa"
          region: "North America"
          population: 37674517
          area: 9984670
          languages: [ "English", "French" ]
          flag: https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Canada.svg

    CountryPopulation:
      type: object
      properties:
        population:
          type: integer
          format: int64
          description: Total population of the country
        urban_population:
          type: integer
          format: int64
          description: Total urban population of the country
        rural_population:
          type: integer
          format: int64
          description: Total rural population of the country
      example:
        population: 14442161
        urban_population: 12093199
        rural_population: 2348962

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              description: A specific error code identifying the error.
              example: ERR001
            message:
              type: string
              description: A human-readable description of the error.
              example: An error occurred while processing your request.
            fields:
              type: array
              items:
                type: string
              description: The list of input fields that caused the error.
              example: [ "id" ]
